### ISSUE TITLE
When I run `cargo test`, it fails

### ISSUE THREAD

**Issue by xymostech** [dginev/rust-kpathsea#2]
This is what I'm seeing when running `cargo test`:

```
% cargo test
   Compiling kpathsea v0.1.2 (/Users/xymostech/projects/rust-kpathsea/kpathsea)
    Finished dev [unoptimized + debuginfo] target(s) in 1.15s
     Running target/debug/deps/kpathsea-c60881e25a23d89f

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/find_file-906caf46f5698747

running 1 test
warning: kpathsea: configuration file texmf.cnf not found in these directories: /Users/xymostech/projects/rust-kpathsea/target/debug/deps:/Users/xymostech/projects/rust-kpathsea/target/debug/deps/share/texmf-local/web2c:/Users/xymostech/projects/rust-kpathsea/target/debug/deps/share/texmf-dist/web2c:/Users/xymostech/projects/rust-kpathsea/target/debug/deps/share/texmf/web2c:/Users/xymostech/projects/rust-kpathsea/target/debug/deps/texmf-local/web2c:/Users/xymostech/projects/rust-kpathsea/target/debug/deps/texmf-dist/web2c:/Users/xymostech/projects/rust-kpathsea/target/debug/deps/texmf/web2c:/Users/xymostech/projects/rust-kpathsea/target/debug:/Users/xymostech/projects/rust-kpathsea/target/debug/share/texmf-local/web2c:/Users/xymostech/projects/rust-kpathsea/target/debug/share/texmf-dist/web2c:/Users/xymostech/projects/rust-kpathsea/target/debug/share/texmf/web2c:/Users/xymostech/projects/rust-kpathsea/target/debug/texmf-local/web2c:/Users/xymostech/projects/rust-kpathsea/target/debug/texmf-dist/web2c:/Users/xymostech/projects/rust-kpathsea/target/debug/texmf/web2c:/Users/xymostech/projects/rust-kpathsea/texmf-local/web2c:/Users/xymostech/projects/rust-kpathsea/target:/Users/xymostech/projects/rust-kpathsea/target/share/texmf-local/web2c:/Users/xymostech/projects/rust-kpathsea/target/share/texmf-dist/web2c:/Users/xymostech/projects/rust-kpathsea/target/share/texmf/web2c:/Users/xymostech/projects/rust-kpathsea/target/texmf-local/web2c:/Users/xymostech/projects/rust-kpathsea/target/texmf-dist/web2c:/Users/xymostech/projects/rust-kpathsea/target/texmf/web2c.
test find_latex ... FAILED

failures:

---- find_latex stdout ----
thread 'find_latex' panicked at 'article.cls wasn't detected on this system. Either your TeX/texlive installation or your kpathsea installation are missing/not visible.', kpathsea/tests/find_file.rs:8:12
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    find_latex

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '-p kpathsea --test find_file'
```

When I was playing around with `kpathsea`, I thought that the program path that you passed into `kpathsea_set_program_name` had to be within the same general vicinity as the tex distribution. Based on the paths that it is searching that seems to be the case. Changing `program_name` to be the path to the `tex` executable causes the tests to pass.

Do the tests pass for you by default on your system? I'm seeing that they're passing on travis-ci which is surprising to me.

**Comment by dginev** [comment]
Indeed, on my ubuntu dev machine tests passed by default without ever having to concern myself additionally with paths *if* I have all the packages specified in `.travis.yml` installed. 

When I was reading (at a very quick glance) the kpathsea docs, they seemed to suggest that I ought to pass the path of the current executable in, which is what I followed and since it worked I didn't question it further. Will go back and reread in detail that section of the docs, thanks for letting me know!

**Comment by dginev** [comment]
There seems to be a (potentially unrelated) issue that breaks `cargo test` non-deterministically - in essence 1 of 3 test calls fails on my machine with:
```
running 2 tests
lstat(/home/home) failed: lstat(/home/home) failed: /home/home: No such file or directory
kpathsea: Can't get directory of program name: /home/deyan/git/rust-kpathsea/target/debug/deps/find_file-a9ff8423308398ce
/home/home: No such file or directory
kpathsea: Can't get directory of program name: /home/deyan/git/rust-kpathsea/target/debug/deps/find_file-a9ff8423308398ce
error: test failed, to rerun pass '-p kpathsea --test find_file'
```

Bookkeeping here for now.

**Comment by xymostech** [comment]
Ooooookay, I spent a bit too much time figuring out how to make this work, but I think I've got it. After many hours of googling for different combinations of things and reading through the kpathsea source, I finally found someone with the same problem that I'm having: https://tug.org/pipermail/tex-k/2010-April/002153.html (For posterity's sake, apparently the magic search terms you need to find this thread are `"kpathsea_set_program_name" argv[0]`) A summary: kpathsea does indeed use the actual path of the executable to figure out where to look for things. In particular, there are two really important things that it derives from this:

* The root directory of the TeX distribution (held in the `$TEXMFROOT` environment variable)
* The location of the texmf.cnf configuration file (held in the `$TEXMFCNF` environment variable)

All of the other important variables are derived from `$TEXMFROOT`, but that is done in texmf.cnf, which is why we need to explicitly point it to that. Luckily, since these things are stored in environment variables, I can just override them instead of having kpathsea getting them from the program name! So if I run the tests like

```
TEXMFCNF=/usr/local/texlive/2018/texmf-dist/web2c \
  TEXMFROOT=/usr/local/texlive/2018 \
  cargo test
```

then they pass!

I'm not entirely sure if this is the correct solution for this library, though. I guess it makes sense in general that I need to tell kpathsea where to look for all of the TeX files, but this isn't the greatest way of doing it (and it sure as hell isn't documented anywhere, which also makes me worried that I might be missing something). I'm guessing that the designers of kpathsea didn't expect people to be using it as a library outside of the programs that are bundled with TeX, so they didn't expect this would come up.

Either way, I'm fine with just exporting those environment variables when I need to use the program. It's not super nice, but it works for me for now. At least we should document this somewhere, and maybe we should make this easier?

**Comment by dginev** [comment]
Scary about the amount of digging you had to go through... thank you for tracking all of these details down! It's all news to me.

I agree it's best to add this to the crate docs. I am still wondering why the default kpathsea fishing fails for your setup, but works on the usual linux box with texlive installed. Your paths suggest you're also using the usual texlive toolchain, so I wonder where exactly things go wrong...

**Comment by dginev** [comment]
Alright, I figured out why it works on a standard Ubuntu image with texlive -- it is set up as part of the internal defaults of kpathsea to look into the "usual" linux paths, particularly in `kpathsea/paths.h`. My path for web2c is indeed the default one:
```
$ ls /usr/share/texmf/web2c
fmtutil.cnf  texmf.cnf  texmfcnf.lua  updmap.cfg
```

So this rule in paths.h works out:
```c
#ifndef DEFAULT_TEXMFCNF
#define DEFAULT_TEXMFCNF "{/etc/texmf/web2c,/usr/local/share/texmf/web2c,/usr/share/texmf/web2c,/usr/share/texlive/texmf-dist/web2c,$SELFAUTOPARENT/share/texmf/web2c}"
#endif
```

I think I now understand what you meant by 
"I'm guessing that the designers of kpathsea didn't expect people to be using it as a library outside of the programs that are bundled with TeX, so they didn't expect this would come up."

This indeed seems to be the case. Wondering if we can just do the equivalent of a `dirname $(which kpsewhich)` in `build.rs` and use that as a constant from where to derive and set `TEXMFROOT` and `TEXMFCNF`, if unset during the main kpathsea logic...

**Comment by dginev** [comment]
There seems to be a helpful crate for running which from Rust: https://crates.io/crates/which

So, thinking out loud, we could grab the directory of the standard `kpsewhich` and pretend to be in it, for purposes of the `Kpaths::new` call. Could work for all setups? Let me know if you'd like to try -- it's difficult for me to see if it improves the situation since I don't have a machine I can test on.
